# Generated by Django 5.2.16 on 2026-08-26 08:55

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('m0_platform_web', '0011_scoped_deepseek_configuration'),
    ]

    operations = [
        migrations.CreateModel(
            name='AssessmentProjectionReceipt',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('attempt_id', models.CharField(max_length=128, unique=True)),
                ('paper_id', models.CharField(max_length=128)),
                ('task_type', models.CharField(max_length=32)),
                ('scoring_checksum', models.CharField(max_length=64)),
                ('applied_at', models.DateTimeField(auto_now_add=True)),
                ('learner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assessment_projection_receipts', to=settings.AUTH_USER_MODEL)),
                ('workspace', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assessment_projection_receipts', to='m0_platform_web.courseclassworkspace')),
            ],
        ),
        migrations.CreateModel(
            name='LearnerConceptMastery',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('concept_id', models.CharField(max_length=80)),
                ('attempted_count', models.PositiveBigIntegerField(default=0)),
                ('correct_count', models.PositiveBigIntegerField(default=0)),
                ('attempt_status', models.CharField(choices=[('unseen', 'Unseen'), ('attempted', 'Attempted')], default='unseen', max_length=16)),
                ('mastery', models.DecimalField(decimal_places=3, default=0, max_digits=4)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('learner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='concept_masteries', to=settings.AUTH_USER_MODEL)),
                ('workspace', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='learner_masteries', to='m0_platform_web.courseclassworkspace')),
            ],
            options={
                'indexes': [models.Index(fields=['workspace', 'learner', 'mastery'], name='m0_mastery_selection_idx')],
                'constraints': [models.UniqueConstraint(fields=('workspace', 'learner', 'concept_id'), name='m0_mastery_scope_learner_concept_unique'), models.CheckConstraint(condition=models.Q(('correct_count__lte', models.F('attempted_count'))), name='m0_mastery_correct_lte_attempted'), models.CheckConstraint(condition=models.Q(('mastery__gte', 0), ('mastery__lte', 0.9)), name='m0_mastery_capped_range'), models.CheckConstraint(condition=models.Q(models.Q(('attempt_status', 'unseen'), ('attempted_count', 0), ('correct_count', 0), ('mastery', 0)), models.Q(('attempt_status', 'attempted'), ('attempted_count__gt', 0)), _connector='OR'), name='m0_mastery_attempt_status_consistent')],
            },
        ),
        migrations.CreateModel(
            name='WrongQuestionRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('item_id', models.CharField(max_length=128)),
                ('item_version', models.CharField(max_length=128)),
                ('latest_attempt_id', models.CharField(max_length=128)),
                ('wrong_count', models.PositiveBigIntegerField(default=1)),
                ('status', models.CharField(choices=[('open', 'Open'), ('resolved', 'Resolved'), ('retired', 'Retired')], default='open', max_length=16)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('learner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='wrong_questions', to=settings.AUTH_USER_MODEL)),
                ('workspace', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='wrong_questions', to='m0_platform_web.courseclassworkspace')),
            ],
            options={
                'indexes': [models.Index(fields=['workspace', 'learner', 'status'], name='m0_wrong_selection_idx')],
                'constraints': [models.UniqueConstraint(fields=('workspace', 'learner', 'item_id'), name='m0_wrong_scope_learner_item_unique'), models.CheckConstraint(condition=models.Q(('wrong_count__gte', 1)), name='m0_wrong_positive_count')],
            },
        ),
    ]
