# Generated by Django 5.2.16 on 2026-08-26 09:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('m0_platform_web', '0012_learning_profile_projection'),
    ]

    operations = [
        migrations.AddField(
            model_name='assessmentprojectionreceipt',
            name='projection_payload',
            field=models.JSONField(default=dict),
        ),
    ]
