# Generated by Django 5.2.16 on 2026-08-26

import uuid

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("m0_platform_web", "0013_assessment_projection_revisions"),
    ]

    operations = [
        migrations.CreateModel(
            name="KnowledgeExtractionBatchCheckpoint",
            fields=[
                (
                    "checkpoint_id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("batch_id", models.CharField(max_length=128)),
                ("batch_index", models.PositiveIntegerField()),
                ("character_count", models.PositiveIntegerField()),
                (
                    "execution_checksum",
                    models.CharField(
                        max_length=64,
                        validators=[
                            django.core.validators.RegexValidator(
                                regex="^[0-9a-f]{64}$",
                            )
                        ],
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("succeeded", "Succeeded"),
                            ("failed", "Failed"),
                        ],
                        max_length=16,
                    ),
                ),
                ("candidates", models.JSONField(default=list)),
                ("evidence_chunks", models.JSONField(default=list)),
                ("retry_count", models.PositiveIntegerField(default=0)),
                (
                    "error_code",
                    models.CharField(blank=True, max_length=64, null=True),
                ),
                (
                    "exception_type",
                    models.CharField(blank=True, max_length=128, null=True),
                ),
                ("completed_at", models.DateTimeField()),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "job",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="extraction_batch_checkpoints",
                        to="m0_platform_web.knowledgeingestionjob",
                    ),
                ),
            ],
            options={
                "indexes": [
                    models.Index(
                        fields=["job", "status", "batch_index"],
                        name="m0_extract_checkpoint_idx",
                    )
                ],
                "constraints": [
                    models.UniqueConstraint(
                        fields=("job", "batch_id"),
                        name="m0_extract_checkpoint_unique",
                    )
                ],
            },
        ),
    ]
