# Generated by Django 5.2.16 on 2026-08-27

import django.core.validators
import django.db.models.deletion
import uuid

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("m0_platform_web", "0014_knowledge_extraction_batch_checkpoint"),
    ]

    operations = [
        migrations.CreateModel(
            name="ClassLearningSnapshot",
            fields=[
                (
                    "snapshot_id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "input_checksum",
                    models.CharField(
                        max_length=64,
                        validators=[
                            django.core.validators.RegexValidator(
                                regex="^[0-9a-f]{64}$"
                            )
                        ],
                    ),
                ),
                (
                    "roster_checksum",
                    models.CharField(
                        max_length=64,
                        validators=[
                            django.core.validators.RegexValidator(
                                regex="^[0-9a-f]{64}$"
                            )
                        ],
                    ),
                ),
                ("active_student_count", models.PositiveIntegerField(default=0)),
                ("reason", models.CharField(max_length=32)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "release",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="class_learning_snapshots",
                        to="m0_platform_web.courseknowledgerelease",
                    ),
                ),
                (
                    "workspace",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="class_learning_snapshots",
                        to="m0_platform_web.courseclassworkspace",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="ClassConceptLearningSnapshot",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("concept_id", models.CharField(max_length=80)),
                ("concept_name", models.CharField(max_length=255)),
                ("attempted_student_count", models.PositiveIntegerField(default=0)),
                ("unattempted_student_count", models.PositiveIntegerField(default=0)),
                ("attempted_item_count", models.PositiveBigIntegerField(default=0)),
                ("correct_item_count", models.PositiveBigIntegerField(default=0)),
                (
                    "average_mastery",
                    models.DecimalField(decimal_places=3, default=0, max_digits=4),
                ),
                ("priority_support_count", models.PositiveIntegerField(default=0)),
                (
                    "priority_support_rate",
                    models.DecimalField(decimal_places=3, default=0, max_digits=4),
                ),
                (
                    "snapshot",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="concepts",
                        to="m0_platform_web.classlearningsnapshot",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="LearningProfileProjectionEvent",
            fields=[
                (
                    "event_id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("attempt_id", models.CharField(max_length=128)),
                ("task_type", models.CharField(max_length=32)),
                (
                    "previous_scoring_checksum",
                    models.CharField(
                        blank=True,
                        max_length=64,
                        null=True,
                        validators=[
                            django.core.validators.RegexValidator(
                                regex="^[0-9a-f]{64}$"
                            )
                        ],
                    ),
                ),
                (
                    "scoring_checksum",
                    models.CharField(
                        max_length=64,
                        validators=[
                            django.core.validators.RegexValidator(
                                regex="^[0-9a-f]{64}$"
                            )
                        ],
                    ),
                ),
                ("changed_concept_ids", models.JSONField(default=list)),
                ("reason", models.CharField(max_length=32)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "learner",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="learning_profile_projection_events",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "snapshot",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="projection_events",
                        to="m0_platform_web.classlearningsnapshot",
                    ),
                ),
                (
                    "workspace",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="learning_profile_projection_events",
                        to="m0_platform_web.courseclassworkspace",
                    ),
                ),
            ],
        ),
        migrations.AddIndex(
            model_name="classlearningsnapshot",
            index=models.Index(
                fields=["workspace", "created_at"],
                name="m5_class_snapshot_latest_idx",
            ),
        ),
        migrations.AddConstraint(
            model_name="classlearningsnapshot",
            constraint=models.UniqueConstraint(
                fields=("workspace", "input_checksum"),
                name="m5_class_snapshot_input_unique",
            ),
        ),
        migrations.AddIndex(
            model_name="classconceptlearningsnapshot",
            index=models.Index(
                fields=["snapshot", "concept_id"],
                name="m5_class_snapshot_concept_idx",
            ),
        ),
        migrations.AddConstraint(
            model_name="classconceptlearningsnapshot",
            constraint=models.UniqueConstraint(
                fields=("snapshot", "concept_id"),
                name="m5_class_snapshot_concept_unique",
            ),
        ),
        migrations.AddConstraint(
            model_name="classconceptlearningsnapshot",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    ("correct_item_count__lte", models.F("attempted_item_count"))
                ),
                name="m5_class_snapshot_correct_lte_attempted",
            ),
        ),
        migrations.AddConstraint(
            model_name="classconceptlearningsnapshot",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    ("average_mastery__gte", 0), ("average_mastery__lte", 0.9)
                ),
                name="m5_class_snapshot_mastery_range",
            ),
        ),
        migrations.AddConstraint(
            model_name="classconceptlearningsnapshot",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    (
                        "priority_support_rate__gte",
                        0,
                    ),
                    ("priority_support_rate__lte", 1),
                ),
                name="m5_class_snapshot_support_rate_range",
            ),
        ),
        migrations.AddIndex(
            model_name="learningprofileprojectionevent",
            index=models.Index(
                fields=["workspace", "created_at"],
                name="m5_profile_event_latest_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="learningprofileprojectionevent",
            index=models.Index(
                fields=["learner", "attempt_id"],
                name="m5_profile_event_learner_idx",
            ),
        ),
        migrations.AddConstraint(
            model_name="learningprofileprojectionevent",
            constraint=models.UniqueConstraint(
                fields=("workspace", "attempt_id", "scoring_checksum"),
                name="m5_profile_event_idempotency_unique",
            ),
        ),
    ]
