# Generated by Django 5.2.16 on 2026-08-27

import django.db.models.deletion

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        (
            "m0_platform_web",
            "0015_classlearningsnapshot_classconceptlearningsnapshot_and_more",
        ),
    ]

    operations = [
        migrations.CreateModel(
            name="TeacherItemReviewNote",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("attempt_id", models.CharField(max_length=128)),
                ("paper_id", models.CharField(max_length=128)),
                ("item_instance_id", models.CharField(max_length=128)),
                ("audit_id", models.CharField(max_length=128)),
                ("audit_version", models.PositiveIntegerField()),
                ("score", models.DecimalField(decimal_places=3, max_digits=9)),
                ("max_score", models.DecimalField(decimal_places=3, max_digits=9)),
                ("teacher_note", models.TextField(blank=True, default="")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "learner",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="teacher_item_review_notes",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "reviewed_by",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="authored_item_review_notes",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "workspace",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="teacher_item_review_notes",
                        to="m0_platform_web.courseclassworkspace",
                    ),
                ),
            ],
            options={
                "indexes": [
                    models.Index(
                        fields=["workspace", "learner", "attempt_id"],
                        name="m0_item_review_note_lookup_idx",
                    ),
                    models.Index(
                        fields=["attempt_id", "item_instance_id", "audit_version"],
                        name="m0_item_note_version_idx",
                    ),
                ],
                "constraints": [
                    models.UniqueConstraint(
                        fields=("attempt_id", "item_instance_id", "audit_version"),
                        name="m0_item_review_note_version_unique",
                    ),
                    models.CheckConstraint(
                        condition=models.Q(
                            ("score__gte", 0),
                            ("score__lte", models.F("max_score")),
                        ),
                        name="m0_item_review_note_score_range",
                    ),
                ],
            },
        ),
    ]
