# Generated by Django 5.2.16 on 2026-08-28

import django.db.models.deletion
from django.conf import settings
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("m0_platform_web", "0016_teacheritemreviewnote"),
    ]

    operations = [
        migrations.CreateModel(
            name="SuggestedTeacherReviewCase",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("attempt_id", models.CharField(max_length=128)),
                ("paper_id", models.CharField(max_length=128)),
                ("task_type", models.CharField(max_length=32)),
                (
                    "scoring_checksum",
                    models.CharField(
                        max_length=64,
                        validators=[
                            django.core.validators.RegexValidator(
                                regex="^[0-9a-f]{64}$"
                            )
                        ],
                    ),
                ),
                ("attempted_at", models.DateTimeField()),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("open", "Open"),
                            ("resolved", "Resolved"),
                            ("superseded", "Superseded"),
                        ],
                        default="open",
                        max_length=16,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "learner",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="suggested_teacher_review_cases",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "workspace",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="suggested_teacher_review_cases",
                        to="m0_platform_web.courseclassworkspace",
                    ),
                ),
            ],
            options={
                "indexes": [
                    models.Index(
                        fields=["workspace", "status", "attempted_at"],
                        name="m0_suggested_case_queue_idx",
                    )
                ],
                "constraints": [
                    models.UniqueConstraint(
                        fields=("workspace", "attempt_id", "paper_id"),
                        name="m0_suggested_review_case_unique",
                    )
                ],
            },
        ),
        migrations.CreateModel(
            name="SuggestedTeacherReviewItem",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("item_instance_id", models.CharField(max_length=128)),
                ("audit_id", models.CharField(max_length=128)),
                ("audit_version", models.PositiveIntegerField()),
                (
                    "confidence",
                    models.DecimalField(decimal_places=3, max_digits=4),
                ),
                ("review_reasons", models.JSONField(default=list)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("open", "Open"),
                            ("resolved", "Resolved"),
                            ("superseded", "Superseded"),
                        ],
                        default="open",
                        max_length=16,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "case",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="items",
                        to="m0_platform_web.suggestedteacherreviewcase",
                    ),
                ),
            ],
            options={
                "indexes": [
                    models.Index(
                        fields=["case", "status", "item_instance_id"],
                        name="m0_suggested_item_queue_idx",
                    )
                ],
                "constraints": [
                    models.UniqueConstraint(
                        fields=("case", "item_instance_id", "audit_version"),
                        name="m0_suggested_review_item_unique",
                    ),
                    models.CheckConstraint(
                        condition=models.Q(
                            ("confidence__gte", 0),
                            ("confidence__lte", 1),
                        ),
                        name="m0_suggested_item_conf_range",
                    ),
                ],
            },
        ),
    ]
