# Generated by Django 5.2.16 on 2026-08-28 13:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('m0_platform_web', '0017_suggested_teacher_review'),
    ]

    operations = [
        migrations.AddField(
            model_name='wrongquestionrecord',
            name='active_follow_up_item_id',
            field=models.CharField(blank=True, default='', max_length=128),
        ),
        migrations.AddField(
            model_name='wrongquestionrecord',
            name='active_follow_up_paper_id',
            field=models.CharField(blank=True, default='', max_length=128),
        ),
        migrations.AddField(
            model_name='wrongquestionrecord',
            name='hint_revealed',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='wrongquestionrecord',
            name='resolved_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='wrongquestionrecord',
            name='resolved_through_attempt_id',
            field=models.CharField(blank=True, default='', max_length=128),
        ),
        migrations.AddField(
            model_name='wrongquestionrecord',
            name='source_item_instance_id',
            field=models.CharField(blank=True, default='', max_length=128),
        ),
        migrations.AddField(
            model_name='wrongquestionrecord',
            name='source_paper_id',
            field=models.CharField(blank=True, default='', max_length=128),
        ),
        migrations.AddIndex(
            model_name='wrongquestionrecord',
            index=models.Index(fields=['workspace', 'active_follow_up_paper_id'], name='m0_wrong_followup_idx'),
        ),
    ]
