# Generated by Django 5.2.16 on 2026-08-28 13:48

from django.db import migrations, models


def remove_non_profile_receipts(apps, schema_editor):
    del schema_editor
    receipt = apps.get_model("m0_platform_web", "AssessmentProjectionReceipt")
    receipt.objects.exclude(
        task_type__in=("diagnostic", "stage_assessment")
    ).delete()


class Migration(migrations.Migration):

    dependencies = [
        ('m0_platform_web', '0018_correction_state_source_of_truth'),
    ]

    operations = [
        migrations.RunPython(remove_non_profile_receipts, migrations.RunPython.noop),
        migrations.AddConstraint(
            model_name='assessmentprojectionreceipt',
            constraint=models.CheckConstraint(condition=models.Q(('task_type__in', ('diagnostic', 'stage_assessment'))), name='m0_projection_profile_task_only'),
        ),
    ]
