# Generated by Django 5.2.16 on 2026-08-29 12:51

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


def migrate_live_governance(apps, schema_editor):
    User = apps.get_model('m0_platform_web', 'User')
    ActorGrant = apps.get_model('m0_platform_web', 'ActorGrant')
    Workspace = apps.get_model('m0_platform_web', 'CourseClassWorkspace')
    Membership = apps.get_model('m0_platform_web', 'ClassMembership')

    administrator_ids = ActorGrant.objects.filter(
        is_active=True,
        role='system_admin',
    ).values_list('user_id', flat=True)
    teacher_ids = ActorGrant.objects.filter(
        is_active=True,
        role__in=('teacher', 'course_admin'),
    ).values_list('user_id', flat=True)
    User.objects.filter(pk__in=teacher_ids).update(account_type='teacher')
    User.objects.filter(pk__in=administrator_ids).update(account_type='administrator')

    for workspace in Workspace.objects.all().iterator():
        owner_ids = list(
            ActorGrant.objects.filter(
                is_active=True,
                role='teacher',
                course_id=workspace.course_id,
                class_id=workspace.class_id,
            )
            .order_by('user_id')
            .values_list('user_id', flat=True)
            .distinct()
        )
        if len(owner_ids) > 1:
            raise RuntimeError(
                'ambiguous teacher ownership for '
                f'{workspace.course_id}/{workspace.class_id}'
            )
        owner_id = owner_ids[0] if owner_ids else None
        if owner_id is not None:
            Workspace.objects.filter(pk=workspace.pk).update(
                owner_teacher_id=owner_id,
            )

        student_ids = ActorGrant.objects.filter(
            is_active=True,
            role='student',
            course_id=workspace.course_id,
            class_id=workspace.class_id,
        ).values_list('user_id', flat=True)
        for student_id in student_ids.iterator():
            Membership.objects.get_or_create(
                workspace_id=workspace.pk,
                student_id=student_id,
                status='active',
                defaults={'added_by_teacher_id': owner_id},
            )


def reverse_live_governance(apps, schema_editor):
    return None


class Migration(migrations.Migration):

    dependencies = [
        ('m0_platform_web', '0019_profile_receipt_constraint'),
    ]

    operations = [
        migrations.CreateModel(
            name='DeletedActorFingerprint',
            fields=[
                ('target_digest', models.CharField(max_length=64, primary_key=True, serialize=False)),
                ('deleted_at', models.DateTimeField(default=django.utils.timezone.now)),
            ],
        ),
        migrations.AlterModelOptions(
            name='actorgrant',
            options={'permissions': [('start_assessment', 'Can start an assessment'), ('submit_assessment', 'Can submit an assessment'), ('view_own_result', 'Can view own assessment result'), ('view_own_feedback', 'Can view own assessment feedback'), ('view_class_analytics', 'Can view class analytics'), ('view_student_report', 'Can view student reports'), ('review_score', 'Can review assessment scores'), ('configure_deepseek', 'Can configure the DeepSeek API'), ('manage_course_knowledge', 'Can manage course knowledge'), ('ask_course_question', 'Can ask cited course questions'), ('view_course_files', 'Can view published course files'), ('manage_course_roles', 'Can manage course roles'), ('manage_platform', 'Can manage the platform'), ('manage_accounts', 'Can create and delete accounts'), ('open_class', 'Can create a course class'), ('manage_class_members', 'Can manage class members')]},
        ),
        migrations.AddField(
            model_name='courseclassworkspace',
            name='class_display_name',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
        migrations.AddField(
            model_name='courseclassworkspace',
            name='course_display_name',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
        migrations.AddField(
            model_name='courseclassworkspace',
            name='owner_teacher',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='owned_course_class_workspaces', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='courseclassworkspace',
            name='roster_version',
            field=models.PositiveBigIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='courseclassworkspace',
            name='status',
            field=models.CharField(choices=[('active', 'Active'), ('archived', 'Archived')], default='active', max_length=16),
        ),
        migrations.AddField(
            model_name='user',
            name='account_type',
            field=models.CharField(choices=[('student', 'Student'), ('teacher', 'Teacher'), ('administrator', 'Administrator')], default='student', max_length=16),
        ),
        migrations.AddConstraint(
            model_name='user',
            constraint=models.CheckConstraint(condition=models.Q(('account_type__in', ['student', 'teacher', 'administrator'])), name='m0_user_account_type_valid'),
        ),
        migrations.AlterField(
            model_name='coursesource',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='course_sources', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='knowledgeingestionjob',
            name='requested_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='knowledge_ingestion_jobs', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='teacheritemreviewnote',
            name='reviewed_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='authored_item_review_notes', to=settings.AUTH_USER_MODEL),
        ),
        migrations.CreateModel(
            name='AuthenticatedSession',
            fields=[
                ('session_key', models.CharField(max_length=40, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='authenticated_sessions', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='AccountLifecycleEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(choices=[('created', 'Created'), ('deletion_started', 'Deletion started'), ('deleted', 'Deleted'), ('delete_failed', 'Deletion failed')], max_length=32)),
                ('target_digest', models.CharField(db_index=True, max_length=64)),
                ('target_account_type', models.CharField(max_length=16)),
                ('request_id', models.CharField(blank=True, default='', max_length=64)),
                ('success', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('administrator', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='account_lifecycle_events', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'indexes': [models.Index(fields=['created_at', 'action'], name='m0_account_event_time_idx')],
            },
        ),
        migrations.CreateModel(
            name='ClassMembership',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('active', 'Active'), ('removed', 'Removed')], default='active', max_length=16)),
                ('joined_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('removed_at', models.DateTimeField(blank=True, null=True)),
                ('added_by_teacher', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='class_memberships_added', to=settings.AUTH_USER_MODEL)),
                ('removed_by_teacher', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='class_memberships_removed', to=settings.AUTH_USER_MODEL)),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='class_memberships', to=settings.AUTH_USER_MODEL)),
                ('workspace', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='memberships', to='m0_platform_web.courseclassworkspace')),
            ],
            options={
                'indexes': [models.Index(fields=['workspace', 'status', 'student'], name='m0_membership_roster_idx'), models.Index(fields=['student', 'status', 'workspace'], name='m0_membership_student_idx')],
                'constraints': [models.UniqueConstraint(condition=models.Q(('status', 'active')), fields=('workspace', 'student'), name='m0_membership_unique_active_student'), models.CheckConstraint(condition=models.Q(models.Q(('removed_at__isnull', True), ('status', 'active')), models.Q(('removed_at__isnull', False), ('status', 'removed')), _connector='OR'), name='m0_membership_status_removed_at')],
            },
        ),
        migrations.RunPython(
            migrate_live_governance,
            reverse_live_governance,
        ),
    ]
