# Generated by Django 5.2.16 on 2026-08-29 13:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('m0_platform_web', '0020_account_class_governance'),
    ]

    operations = [
        migrations.AddField(
            model_name='courseclassworkspace',
            name='creation_token_digest',
            field=models.CharField(blank=True, max_length=64, null=True, unique=True),
        ),
    ]
