# Generated by Django 5.2.16 on 2026-08-30

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


def clear_legacy_identity_derived_state(apps, schema_editor):
    """Erase historical name-derived hashes that cannot be linked safely."""

    AccountLifecycleEvent = apps.get_model(
        "m0_platform_web", "AccountLifecycleEvent"
    )
    LoginFailureBucket = apps.get_model(
        "m0_platform_web", "LoginFailureBucket"
    )
    AccountLifecycleEvent.objects.all().delete()
    LoginFailureBucket.objects.all().delete()


class Migration(migrations.Migration):

    dependencies = [
        ("m0_platform_web", "0026_backfill_workspace_display_names"),
    ]

    operations = [
        migrations.AddField(
            model_name="accountlifecycleevent",
            name="target_user",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="account_lifecycle_target_events",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="loginfailurebucket",
            name="account_user",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="login_failure_buckets",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.RunPython(
            clear_legacy_identity_derived_state,
            migrations.RunPython.noop,
        ),
        migrations.RemoveField(
            model_name="accountlifecycleevent",
            name="target_digest",
        ),
        migrations.AlterField(
            model_name="accountlifecycleevent",
            name="target_user",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="account_lifecycle_target_events",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.DeleteModel(
            name="DeletedActorFingerprint",
        ),
    ]
