"""Public contract registry for the course-insight modular monolith."""

from course_insight.contracts.base import ContractModel
from course_insight.contracts.assessment import (
    AssessmentPaper,
    CriterionScore,
    ItemInstance,
    PaperSection,
    RemediationPlan,
    RemediationTarget,
    RubricScoringResult,
    RubricScoringTask,
    ScoreAuditRecord,
    ScoringPreparationResult,
    ScoringResultBundle,
)
from course_insight.contracts.analytics import (
    ClassReport,
    CriterionOverride,
    IndividualReport,
    ReviewQueueItem,
    TeacherAnalyticsBundle,
    TeacherReviewDecision,
    TeachingSuggestion,
)
from course_insight.contracts.course import (
    ContentChunk,
    CoursePackage,
    SourceAuthorization,
    SourceDocument,
)
from course_insight.contracts.errors import DomainError
from course_insight.contracts.events import EventAck, LearningEvent
from course_insight.contracts.evidence import (
    EvidenceBundle,
    EvidenceChunk,
    EvidenceIndexRef,
    EvidenceQuery,
)
from course_insight.contracts.intelligence import (
    ArchitectureScaffoldResult,
    EmbeddingModelRef,
    LLMGenerationRequest,
    LLMGenerationResult,
    LLMModelRef,
    ModelInvocationAudit,
    RetrievalAudit,
    RetrievalPolicy,
    SafetyCheckResult,
)
from course_insight.contracts.knowledge import (
    AssessmentBlueprint,
    BlueprintSection,
    ItemCard,
    KnowledgeBundle,
    KnowledgeConcept,
    MisconceptionTag,
    ParameterRule,
    PrerequisiteRelation,
    QMatrixEntry,
    ReviewPolicy,
    Rubric,
    RubricCriterion,
)
from course_insight.contracts.learning_models import (
    AbilityEstimate,
    AdaptiveSelectionPolicy,
    AdaptiveSelectionResult,
    CalibrationReviewDecision,
    CalibrationRunResult,
    BktConceptParameters,
    BktModelArtifact,
    ConceptResponse,
    ConceptResponseSequence,
    CognitiveDiagnosisResult,
    DinaItemParameters,
    DinaModelArtifact,
    IRTItemParameters,
    IRTParameterSet,
    ItemExposureSnapshot,
    KnowledgeTraceSnapshot,
    LearningModelRun,
    LearningObservation,
    LearningObservationBatch,
    ModelQualityReport,
)
from course_insight.contracts.platform import (
    ActorContext,
    AssessmentSubmission,
    AsyncJobStatus,
    TeacherReviewSubmission,
)
from course_insight.contracts.state import (
    ClassConceptStatus,
    ClassMisconceptionSummary,
    ClassStateSnapshot,
    ConceptState,
    DiagnosisResult,
    ItemDiagnosis,
    LearnerStateSnapshot,
    MasteryDistribution,
    MisconceptionStrength,
    StateUpdateResult,
)
from course_insight.contracts.tasking import TaskPlan
from course_insight.contracts.tutoring import (
    EvidenceCitation,
    FeedbackGenerationTask,
    RubricFeedback,
    SessionStateSnapshot,
    StudentFeedbackPackage,
    TeachingAction,
    TutoringControlResult,
)

__all__ = [
    "AbilityEstimate",
    "ActorContext",
    "AdaptiveSelectionPolicy",
    "AdaptiveSelectionResult",
    "ArchitectureScaffoldResult",
    "AssessmentBlueprint",
    "AssessmentPaper",
    "AssessmentSubmission",
    "AsyncJobStatus",
    "BlueprintSection",
    "CalibrationReviewDecision",
    "CalibrationRunResult",
    "BktConceptParameters",
    "BktModelArtifact",
    "ClassConceptStatus",
    "ClassMisconceptionSummary",
    "ClassReport",
    "ClassStateSnapshot",
    "ConceptState",
    "ConceptResponse",
    "ConceptResponseSequence",
    "ContentChunk",
    "ContractModel",
    "CognitiveDiagnosisResult",
    "DinaItemParameters",
    "DinaModelArtifact",
    "CoursePackage",
    "CriterionOverride",
    "CriterionScore",
    "DiagnosisResult",
    "DomainError",
    "EventAck",
    "EvidenceBundle",
    "EvidenceChunk",
    "EvidenceCitation",
    "EvidenceIndexRef",
    "EvidenceQuery",
    "EmbeddingModelRef",
    "FeedbackGenerationTask",
    "IndividualReport",
    "IRTItemParameters",
    "IRTParameterSet",
    "ItemExposureSnapshot",
    "ItemCard",
    "ItemDiagnosis",
    "ItemInstance",
    "KnowledgeBundle",
    "KnowledgeConcept",
    "KnowledgeTraceSnapshot",
    "LearnerStateSnapshot",
    "LearningEvent",
    "LearningModelRun",
    "LearningObservation",
    "LearningObservationBatch",
    "LLMGenerationRequest",
    "LLMGenerationResult",
    "LLMModelRef",
    "MasteryDistribution",
    "MisconceptionStrength",
    "MisconceptionTag",
    "ModelInvocationAudit",
    "ModelQualityReport",
    "PaperSection",
    "ParameterRule",
    "PrerequisiteRelation",
    "QMatrixEntry",
    "RemediationPlan",
    "RemediationTarget",
    "ReviewPolicy",
    "ReviewQueueItem",
    "RetrievalAudit",
    "RetrievalPolicy",
    "Rubric",
    "RubricCriterion",
    "RubricFeedback",
    "RubricScoringResult",
    "RubricScoringTask",
    "ScoreAuditRecord",
    "ScoringPreparationResult",
    "ScoringResultBundle",
    "SafetyCheckResult",
    "SessionStateSnapshot",
    "SourceAuthorization",
    "SourceDocument",
    "StateUpdateResult",
    "StudentFeedbackPackage",
    "TaskPlan",
    "TeacherAnalyticsBundle",
    "TeacherReviewSubmission",
    "TeacherReviewDecision",
    "TeachingAction",
    "TeachingSuggestion",
    "TutoringControlResult",
]

# Keep the public registry deterministic for schema export and interface consumers.
__all__ = sorted(__all__)
