"""URL surface owned by the M0 Django boundary."""

from django.urls import path

from course_insight.modules.m0_platform.django_app.views import (
    account_admin,
    auth,
    health,
    knowledge,
    student,
    student_files,
    student_qa,
    teacher,
)


urlpatterns = [
    path("health/live/", health.live, name="health-live"),
    path("health/ready/", health.ready, name="health-ready"),
    path("accounts/login/", auth.login, name="login"),
    path("accounts/logout/", auth.logout, name="logout"),
    path("account-admin/accounts/", account_admin.home, name="account-admin-home"),
    path(
        "account-admin/accounts/teachers/create/",
        account_admin.create_teacher,
        name="account-admin-create-teacher",
    ),
    path(
        "account-admin/accounts/students/create/",
        account_admin.create_student,
        name="account-admin-create-student",
    ),
    path(
        "account-admin/accounts/teachers/<int:user_id>/delete/",
        account_admin.delete_teacher,
        name="account-admin-delete-teacher",
    ),
    path(
        "account-admin/accounts/students/<int:user_id>/delete/",
        account_admin.delete_student,
        name="account-admin-delete-student",
    ),
    path("student/", student.home, name="student-home"),
    path(
        "student/courses/<str:course_id>/classes/<str:class_id>/qa/",
        student_qa.page,
        name="student-qa",
    ),
    path(
        "student/courses/<str:course_id>/classes/<str:class_id>/files/",
        student_files.page,
        name="student-course-files",
    ),
    path(
        (
            "student/courses/<str:course_id>/classes/<str:class_id>/"
            "files/<uuid:source_id>/download/"
        ),
        student_files.download,
        name="student-course-file-download",
    ),
    path(
        "student/select-workspace/",
        student.select_workspace,
        name="student-select-workspace",
    ),
    path(
        (
            "student/courses/<str:course_id>/classes/<str:class_id>/"
            "assessments/start/"
        ),
        student.start,
        name="student-start",
    ),
    path(
        (
            "student/courses/<str:course_id>/classes/<str:class_id>/"
            "assessments/<str:paper_id>/"
        ),
        student.assessment,
        name="student-assessment",
    ),
    path(
        (
            "student/courses/<str:course_id>/classes/<str:class_id>/"
            "assessments/<str:paper_id>/submit/"
        ),
        student.submit,
        name="student-submit",
    ),
    path(
        (
            "student/courses/<str:course_id>/classes/<str:class_id>/"
            "results/<str:paper_id>/"
        ),
        student.result,
        name="student-result",
    ),
    path(
        (
            "student/courses/<str:course_id>/classes/<str:class_id>/"
            "results/<str:paper_id>/correction/"
        ),
        student.correction,
        name="student-correction",
    ),
    path(
        (
            "student/courses/<str:course_id>/classes/<str:class_id>/"
            "results/<str:paper_id>/correction/follow-up/"
        ),
        student.follow_up,
        name="student-follow-up",
    ),
    path(
        (
            "student/courses/<str:course_id>/classes/<str:class_id>/"
            "feedback/<str:paper_id>/"
        ),
        student.feedback,
        name="student-feedback",
    ),
    path("teacher/", teacher.home, name="teacher-home"),
    path("teacher/classes/open/", teacher.open_class, name="teacher-open-class"),
    path(
        "teacher/courses/<str:course_id>/classes/<str:class_id>/students/add/",
        teacher.add_class_student,
        name="teacher-class-add-student",
    ),
    path(
        (
            "teacher/courses/<str:course_id>/classes/<str:class_id>/"
            "students/<int:student_id>/remove/"
        ),
        teacher.remove_class_student,
        name="teacher-class-remove-student",
    ),
    path(
        "teacher/courses/<str:course_id>/classes/<str:class_id>/knowledge/",
        knowledge.page,
        name="teacher-course-knowledge",
    ),
    path(
        "teacher/courses/<str:course_id>/classes/<str:class_id>/knowledge/uploads/",
        knowledge.upload,
        name="teacher-knowledge-upload",
    ),
    path(
        "teacher/courses/<str:course_id>/classes/<str:class_id>/knowledge/stage-delete/",
        knowledge.stage_delete,
        name="teacher-knowledge-stage-delete",
    ),
    path(
        (
            "teacher/courses/<str:course_id>/classes/<str:class_id>/knowledge/"
            "questions/<uuid:source_id>/edit/"
        ),
        knowledge.edit_question,
        name="teacher-knowledge-question-edit",
    ),
    path(
        "teacher/courses/<str:course_id>/classes/<str:class_id>/knowledge/confirm/",
        knowledge.confirm,
        name="teacher-knowledge-confirm",
    ),
    path(
        (
            "teacher/courses/<str:course_id>/classes/<str:class_id>/knowledge/"
            "jobs/<uuid:job_id>/"
        ),
        knowledge.job_status,
        name="teacher-knowledge-job",
    ),
    path(
        "teacher/courses/<str:course_id>/knowledge/",
        knowledge.page,
        name="teacher-course-knowledge",
    ),
    path(
        "teacher/courses/<str:course_id>/knowledge/uploads/",
        knowledge.upload,
        name="teacher-knowledge-upload",
    ),
    path(
        "teacher/courses/<str:course_id>/knowledge/stage-delete/",
        knowledge.stage_delete,
        name="teacher-knowledge-stage-delete",
    ),
    path(
        "teacher/courses/<str:course_id>/knowledge/questions/<uuid:source_id>/edit/",
        knowledge.edit_question,
        name="teacher-knowledge-question-edit",
    ),
    path(
        "teacher/courses/<str:course_id>/knowledge/confirm/",
        knowledge.confirm,
        name="teacher-knowledge-confirm",
    ),
    path(
        "teacher/courses/<str:course_id>/knowledge/jobs/<uuid:job_id>/",
        knowledge.job_status,
        name="teacher-knowledge-job",
    ),
    path(
        (
            "teacher/courses/<str:course_id>/classes/<str:class_id>/"
            "deepseek/"
        ),
        teacher.deepseek_settings,
        name="teacher-deepseek-settings",
    ),
    path(
        "teacher/deepseek/",
        teacher.deepseek_settings,
        name="teacher-deepseek-settings",
    ),
    path("teacher/reviews/", teacher.lookup, name="teacher-review-lookup"),
    path(
        (
            "teacher/courses/<str:course_id>/classes/<str:class_id>/"
            "reviews/learners/<str:learner_id>/"
        ),
        teacher.review_list,
        name="teacher-learner-review-list",
    ),
    path(
        (
            "teacher/courses/<str:course_id>/classes/<str:class_id>/"
            "suggested-reviews/"
        ),
        teacher.suggested_review_list,
        name="teacher-suggested-review-list",
    ),
    path(
        (
            "teacher/courses/<str:course_id>/classes/<str:class_id>/"
            "suggested-reviews/<int:case_id>/"
        ),
        teacher.suggested_review_detail,
        name="teacher-suggested-review-detail",
    ),
    path("teacher/classes/", teacher.class_lookup, name="teacher-class-lookup"),
    path(
        "teacher/knowledge-reviews/",
        teacher.knowledge_lookup,
        name="teacher-knowledge-review-lookup",
    ),
    path(
        "teacher/courses/<str:course_id>/classes/<str:class_id>/",
        teacher.class_context,
        name="teacher-class",
    ),
    path(
        (
            "teacher/courses/<str:course_id>/classes/<str:class_id>/"
            "suggestions/"
        ),
        teacher.decide_class_suggestion,
        name="teacher-class-suggestion",
    ),
    path(
        (
            "teacher/courses/<str:course_id>/classes/<str:class_id>/"
            "teaching-advice/"
        ),
        teacher.generate_class_teaching_advice,
        name="teacher-class-teaching-advice",
    ),
    path(
        (
            "teacher/courses/<str:course_id>/classes/<str:class_id>/"
            "objective-answers/"
        ),
        teacher.objective_answers,
        name="teacher-objective-answers",
    ),
    path(
        (
            "teacher/courses/<str:course_id>/classes/<str:class_id>/"
            "blueprint/"
        ),
        teacher.blueprint,
        name="teacher-blueprint",
    ),
    path(
        (
            "teacher/courses/<str:course_id>/classes/<str:class_id>/"
            "learners/<str:learner_id>/"
        ),
        teacher.learner,
        name="teacher-learner",
    ),
    path(
        (
            "teacher/courses/<str:course_id>/classes/<str:class_id>/"
            "reviews/<str:paper_id>/"
        ),
        teacher.review_context,
        name="teacher-review-context",
    ),
    path(
        (
            "teacher/courses/<str:course_id>/classes/<str:class_id>/"
            "reviews/<str:paper_id>/suggestions/"
        ),
        teacher.decide_suggestion,
        name="teacher-suggestion",
    ),
    path(
        (
            "teacher/courses/<str:course_id>/classes/<str:class_id>/"
            "reviews/<str:paper_id>/rescore/"
        ),
        teacher.rescore,
        name="teacher-rescore",
    ),
    path(
        (
            "teacher/courses/<str:course_id>/classes/<str:class_id>/"
            "reviews/<str:paper_id>/items/<str:item_instance_id>/rescore/"
        ),
        teacher.item_rescore,
        name="teacher-item-rescore",
    ),
    path(
        (
            "teacher/courses/<str:course_id>/classes/<str:class_id>/"
            "reviews/<str:paper_id>/audits/<str:audit_id>/"
        ),
        teacher.review,
        name="teacher-review",
    ),
    path(
        (
            "teacher/courses/<str:course_id>/classes/<str:class_id>/"
            "knowledge-reviews/<str:review_id>/"
        ),
        teacher.knowledge_review,
        name="teacher-knowledge-review",
    ),
]
